# Generated by Django 4.2 on 2023-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0002_alter_memberstatus_options_alter_memberstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(choices=[('1', 'Не стоит внимания'), ('2', 'Так себе'), ('3', 'Сойдёт'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=1, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_question',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Это вопрос'),
        ),
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='member',
            name='meetup',
            field=models.ManyToManyField(related_name='members', through='meetup_bot.MemberStatus', to='meetup_bot.meetup', verbose_name='митап'),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.TimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.TimeField(verbose_name='Дата начала'),
        ),
    ]
