# Generated by Django 4.2 on 2023-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0007_alter_member_about_alter_member_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
